### PR TITLE
Update dependencies

### LINKED ISSUE #56: Fix instrument view with new Plopp
The error is:
```
>       self.fig = self.scatter[0]
E       TypeError: 'Figure' object is not subscriptable
```

### PR DESCRIPTION
**Pull request by jl-wynen**
Supersedes #57 with a cleaner update in all places.

Also fixes #56

### CODE REVIEW

**Comment by YooSunYoung** [comment]
I think it's blocked by this one...?  https://github.com/scipp/essdiffraction/issues/56

**Comment by nvaytet** [comment]
@jl-wynen should I fix the instrument view directly here? Because if I make a PR without updating the dependencies, it won't work with the old version of Plopp.

**Comment by jl-wynen** [comment]
@nvaytet fine by me.

**Comment by nvaytet** [comment]
@jl-wynen it seems we need `scippneutron=24.05` to be able to build the docs, as the `scippneutron.instrument_view` also has a fix in the latest version.

**Comment by jl-wynen** [comment]
This should be fine. ScippNeutron is released.

**Review by nvaytet — APPROVED** [review]

**Pull request merged**
