### PR TITLE
Remove unused domain types

### PR DESCRIPTION
**Pull request by SimonHeybrock**
@celinedurniak were there others that are not needed that you had in mind?

### CODE REVIEW

**Comment by celinedurniak** [comment]
What are `RunType` and `ScatteringRunType`?

**Comment by SimonHeybrock** [comment]
> What are `RunType` and `ScatteringRunType`?

These a type-variables, which will (in the case of powder) take values such as `SampleRun` or `VanadiumRun`. Any data-reduction step that performs identical computation for several run types uses these. Here is an example:

https://github.com/scipp/essdiffraction/blob/7772e6962b7739da6c74e2b809d90d278b61ee58/src/ess/powder/conversion.py#L199-L203

This function will/can be used multiple times in the reduction workflow graph, typically for sample and vanadium runs.

**Comment by celinedurniak** [comment]
And 'NexusSource' is the input raw file?

**Comment by SimonHeybrock** [comment]
> And 'NexusSource' is the input raw file?

It is the NXsource group loaded from a Nexus file. See https://scipp.github.io/essreduce/generated/modules/ess.reduce.nexus.generic_types.html for full list of types and explanations.

**Comment by celinedurniak** [comment]
Thanks for the explanations. 
So, to answer the first question, at the moment, I do not see any more terms to remove.

**Pull request merged**
